### ISSUE TITLE
Support nested mapping for the process

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1304]
When using the mapping function of the process we can now only create inputs based on a flat data structure:

```yml
mapping:
  foo: ref or const
  bar: ref or const
```

It would be nice to be able to support arrays and nested data like in the services and provide a full mapping.

```yml
mapping:
  my:
    nested:
       object: ref or const
   array:
     - ref or const
     - ref or const
```
