### ISSUE TITLE
Reference nested data in mapping

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1306]
Using mapping in processes is now limited to first-level data.

```yml
mapping:
  foo: { nodeKey: xxx, key: outputA }
  bar: { nodeKey: yyy, key: outputB }
```

This is great but quite limited because MESG services support outputs with nested value or array. It would be nice to support it too in the processes with something like:

```yml
mapping:
  foo: { nodeKey: xxx, key: outputObject.outputA }
  bar: { nodeKey: yyy, key: outputX.0.a }
```
