### ISSUE TITLE
Issue with hash calculation

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1328]
When working on https://github.com/mesg-foundation/engine/pull/1316 I discover that whatever the value I add in the constant, the hash will stay the same.

Example:
```yaml
key: Event
steps:
  - type: trigger
    instanceHash: H74Qqq8nT5JZ9GSJmuSWLN5benWZPkUb5pYcvQLsoZX 
    eventKey: eventX
  - type: task
    instanceHash: DTjy36ApV5YVbyXm67iWeAsD9uCbZETcPL1TbUPwHeYJ
    taskKey: taskY
    inputs:
      inputA: hello world
```

and 
```yaml
key: Event
steps:
  - type: trigger
    instanceHash: H74Qqq8nT5JZ9GSJmuSWLN5benWZPkUb5pYcvQLsoZX 
    eventKey: eventX
  - type: task
    instanceHash: DTjy36ApV5YVbyXm67iWeAsD9uCbZETcPL1TbUPwHeYJ
    taskKey: taskY
    inputs:
      inputA: "different value that should change the hash"
```

will generate the same hash
