### ISSUE TITLE
Process steps cannot access to event data if not the first one

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1523]
The process steps cannot access to event data if they are not the first one. Here is a process where step #3 try to access to the trigger's event:
 
```yaml
key: notification
steps:
  - type: trigger
    key: interval
    instance:
      src: https://github.com/mesg-foundation/service-emit-event-interval
    eventKey: every_10_seconds
  - type: task
    instance:
      src: ../service-crypto-tracker
    taskKey: get
    inputs:
      pair: 'btcusd'
      exchange_sym: 'bitfinex'
  - type: task
    instance:
      src: ../service-concat
    taskKey: concat
    inputs:
      p1: 'The price of BTC/USD on Bitfinex is '
      value:
        key: price
      p2: ' $ '
      date:
        stepKey: interval
        key: timestamp
  - type: task
    instance:
      src: ../service-telegram
      env:
        - 'TOKEN=$(env:TOKEN)'
        - 'CHAT_ID=$(env:CHAT_ID)'
    taskKey: pushNotify
```
