### ISSUE TITLE
Issue while configuring the engine with a config file

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1574]
I'm trying to create a config file to customize the CORS access on tendermint but for some reason, I can't. The file is read but trigger some errors like:
```
  line 1: field Tendermint not found in type config.Config  module=main
```

Here is my config:
```yml
Tendermint:
  Config:
    RPC:
      CORSAllowedOrigins:
        - http://localhost:3000
```

I tried a combination of lowerCase, camelCase, underscore... but nothing seems to work.

Am I missing something or is it a bug?

**Comment by NicolasMahe** [comment]
It should be lowercased. But I'm not sure what to put for all uppercase word (`RPC` and `CORSAllowedOrigins`)

@antho1404 if you fix it, can you put the right version and close the issue?

**Comment by antho1404** [comment]
Here is the right version, just everything to lowercase:

```yaml
tendermint:
  config:
    rpc:
      corsallowedorigins:
        - http://localhost:3000
```

This should be added in the documentation somewhere https://github.com/mesg-foundation/engine/issues/1589
