### ISSUE TITLE
Can't access data from event trigger using filter.

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/engine#1581]
**To Reproduce**

1. run the `process.yml` file.
2. Make a transfer some MESG Token as `Ropsten network` or etc.

**Expected behavior**
If a transfer is the same `contractAddress` as filter type in the `process file`. It should do the next step.

**Code in the process.yml file:**
```yml
name: ERC20 notification
steps:
  - type: trigger
    instance:
      src: https://github.com/mesg-foundation/service-ethereum-erc20
      env:
        - PROVIDER_ENDPOINT=$(env:PROVIDER_ENDPOINT)
        - BLOCK_CONFIRMATIONS=0
    eventKey: transfer
  - type: filter
    conditions:
      contractAddress: '0xd14a3d6b94016e455af5eb7f329bc572ea626c5f'
  - type: task
    instance:
      src: https://github.com/mesg-foundation/service-js-function
    taskKey: execute
    inputs:
      code: 'module.exports = (data) => data'
      inputs:
        blockNumber: { key: blockNumber }
        transactionHash: { key: transactionHash }
        from: { key: from }
        to: { key: to }
        value: { key: value }
        contractAddress: { key: contractAddress }
```
