### ISSUE TITLE
The filter can't use condition with nested data.

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/engine#1582]
**To Reproduce**
1. run the `process.yml` file.
2. Make a transfer some MESG Token as `Ropsten network` or etc.

**Expected behavior**
The filer can use condition with nested data from the previous step. 

Example: 
```yml
...
  - type: filter
    conditions:
      result.contractAddress:  "0xd14a3d6b94016e455af5eb7f329bc572ea626c5f"
...
```

**Code in the process.yml file:**
```yml
name: ERC20 notification
steps:
  - type: trigger
    instance:
      src: https://github.com/mesg-foundation/service-ethereum-erc20
      env:
        - PROVIDER_ENDPOINT=$(env:PROVIDER_ENDPOINT)
        - BLOCK_CONFIRMATIONS=0
    eventKey: transfer
  - type: task
    instance:
      src: https://github.com/mesg-foundation/service-js-function
    taskKey: execute
    inputs:
      code: 'module.exports = (data) => data'
      inputs:
        blockNumber: { key: blockNumber }
        transactionHash: { key: transactionHash }
        from: { key: from }
        to: { key: to }
        value: { key: value }
        contractAddress: { key: contractAddress }
    # outputs:
    #   result: Any
  - type: filter
    conditions:
      contractAddress: '0xd14a3d6b94016e455af5eb7f329bc572ea626c5f'
  - type: task
    instance:
      src: https://github.com/mesg-foundation/service-js-function
    taskKey: execute
    inputs:
      code: >
        module.exports = (data) => `Transfer ${data.value} MESG token from ${data.from} to ${data.to}, See the transaction as https://ropsten.etherscan.io/tx/${data.transactionHash}`
      inputs:
        transactionHash: { key: transactionHash }
        from: { key: from }
        to: { key: to }
        value: { key: value }
```
