### ISSUE TITLE
Add example of config file

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1589]
This example could be in the sources, in a wiki or directly in the documentation

For reference, this is the generated config file:

```yaml
ipfsendpoint: http://ipfs.app.mesg.com:8080/ipfs/
server:
  address: :50052
log:
  format: text
  forcecolors: false
  level: info
database:
  instancerelativepath: database/instance/v2
  executionrelativepath: database/executions/v3
  processrelativepath: database/processes/v2
tendermint:
  config:
    baseconfig:
      rootdir: /root/.mesg/tendermint
      proxyapp: tcp://127.0.0.1:26658
      moniker: a986a8894e2e
      fastsyncmode: true
      dbbackend: goleveldb
      dbpath: data
      loglevel: main:info,state:info,*:error
      logformat: plain
      genesis: config/genesis.json
      privvalidatorkey: config/priv_validator_key.json
      privvalidatorstate: data/priv_validator_state.json
      privvalidatorlistenaddr: ""
      nodekey: config/node_key.json
      abci: socket
      proflistenaddress: ""
      filterpeers: false
    rpc:
      rootdir: /root/.mesg/tendermint
      listenaddress: tcp://0.0.0.0:26657
      corsallowedorigins: []
      corsallowedmethods:
      - HEAD
      - GET
      - POST
      corsallowedheaders:
      - Origin
      - Accept
      - Content-Type
      - X-Requested-With
      - X-Server-Time
      grpclistenaddress: ""
      grpcmaxopenconnections: 900
      unsafe: false
      maxopenconnections: 900
      maxsubscriptionclients: 100
      maxsubscriptionsperclient: 5
      timeoutbroadcasttxcommit: 10s
      maxbodybytes: 1000000
      maxheaderbytes: 1048576
      tlscertfile: ""
      tlskeyfile: ""
    p2p:
      rootdir: /root/.mesg/tendermint
      listenaddress: tcp://0.0.0.0:26656
      externaladdress: ""
      seeds: ""
      persistentpeers: ""
      upnp: false
      addrbook: config/addrbook.json
      addrbookstrict: false
      maxnuminboundpeers: 40
      maxnumoutboundpeers: 10
      flushthrottletimeout: 100ms
      maxpacketmsgpayloadsize: 1024
      sendrate: 5120000
      recvrate: 5120000
      pexreactor: true
      seedmode: false
      privatepeerids: ""
      allowduplicateip: true
      handshaketimeout: 20s
      dialtimeout: 3s
      testdialfail: false
      testfuzz: false
      testfuzzconfig:
        mode: 0
        maxdelay: 3s
        probdroprw: 0.2
        probdropconn: 0
        probsleep: 0
    mempool:
      rootdir: /root/.mesg/tendermint
      recheck: true
      broadcast: true
      walpath: ""
      size: 5000
      maxtxsbytes: 1073741824
      cachesize: 10000
      maxtxbytes: 1048576
    fastsync:
      version: v0
    consensus:
      rootdir: /root/.mesg/tendermint
      walpath: data/cs.wal/wal
      timeoutpropose: 3s
      timeoutproposedelta: 500ms
      timeoutprevote: 1s
      timeoutprevotedelta: 500ms
      timeoutprecommit: 1s
      timeoutprecommitdelta: 500ms
      timeoutcommit: 1s
      skiptimeoutcommit: false
      createemptyblocks: true
      createemptyblocksinterval: 0s
      peergossipsleepduration: 100ms
      peerquerymaj23sleepduration: 2s
    txindex:
      indexer: kv
      indextags: ""
      indexalltags: false
    instrumentation:
      prometheus: true
      prometheuslistenaddr: 0.0.0.0:26660
      maxopenconnections: 3
      namespace: tendermint
  relativepath: tendermint
cosmos:
  relativepath: cosmos
devgenesis:
  chainid: mesg-dev-chain
account:
  name: engine
  password: pass
  mnemonic: ""
```

_Originally posted by @antho1404 in https://github.com/mesg-foundation/engine/pull/1578#issuecomment-572876839_
