### ISSUE TITLE
Add yaml (un)marshal functions to hash.Hash struct

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1652]
We should implement the yaml (un)marshal functions in hash.Hash struct for the cmds

Current output:
```
./bin/mesg-cli query ownership list -o text
- hash:
  - 2
  - 36
  - 237
  - 182
  - 176
  - 157
  - 120
  - 189
  - 224
  - 73
  - 187
  - 1
  - 250
  - 167
  - 173
  - 216
  - 197
  - 192
  - 165
  - 15
  - 71
  - 38
  - 113
  - 201
  - 82
  - 55
  - 16
  - 5
  - 0
  - 189
  - 85
  - 217
  owner: mesgtest1mar6djuz8ft9c9arnpazvqj2rjwr03n30mwqtk
  resourcehash:
  - 109
  - 168
  - 58
  - 38
  - 72
  - 243
  - 251
  - 104
  - 115
  - 35
  - 187
  - 177
  - 235
  - 220
  - 85
  - 140
  - 10
  - 186
  - 138
  - 207
  - 233
  - 81
  - 196
  - 85
  - 166
  - 255
  - 128
  - 198
  - 250
  - 167
  - 207
  - 167
  resource: 1
  xxx_nounkeyedliteral: {}
  xxx_unrecognized: []
  xxx_sizecache: 0

```
