### ISSUE TITLE
Process hash calculation

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1707]
The hash of the process is based on the order of the nodes/edges. This doesn't entirely define a process as any order for the edges or nodes will result in the exact same graph.

The 2 following graphs have the same behavior but have different hash
```yml
nodes:
  - eventA
  - taskA
edges:
  from: eventA, to: taskA
```

```yml
nodes:
  - taskA
  - eventA
edges:
  from: eventA, to: taskA
```

One way to solve that is to sort the nodes and edges to make sure that we don't rely on the order given by the user but a deterministic order that we define (based on the node key for example).

Advantages of considering these 2 processes as the same:
- Doesn't rely on the user's input so whatever compiler is used the result will always be the same
- Giving us control on the order of the edges/nodes so we can rearrange the graph to make it more efficient

Disadvantages:
- No optimization possible from the user, reordering some nodes might result in a tiny micro-optimization...

_Originally posted by @antho1404 in https://github.com/mesg-foundation/engine/timeline_

**Comment by krhubert** [comment]
So I like the idea of keeping the same hash for the same logical data. 

Option to consider - instead of storing the array, we can change the types from array to map. In that case, we already have sorting plus it give us the possibility to extend the node in the future.

```yml
nodes:
  eventA:
  taskA:
edges:
  from: eventA, to: taskA
```

> No optimization possible from the user, reordering some nodes might result in a tiny micro-optimization...

Hum I don't think it is worth it... :)
