### ISSUE TITLE
Better handling empty inputs + outputs

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/engine#832]
mesg.yml
```yml

name: test-service

events:
  foo:

tasks:
  foo:
```

```
➜  core git:(benchmark/service) ✗ ./dev-cli service validate ./service
⨯ File 'mesg.yml' is not valid. See documentation: https://docs.mesg.com/guide/service/service-file.html
	* Tasks[foo] is a required field
	* Events[foo] is a required field
```

The information is not clear. Also there was an issue about handle empty data but I can't find it right now so I recreated this one.

**Comment by krhubert** [comment]
+ extra with validation changes service doesn't have an option to return nothing

```yml
name: test-service

tasks:
  foo:
    outputs:
      data:
```

```
⨯ File 'mesg.yml' is not valid. See documentation: https://docs.mesg.com/guide/service/service-file.html
	* Tasks[foo].Outputs[data] is a required field
```
